const { Client } = require('pg');
const fs = require('fs');
require('dotenv').config();

/**
 * Sovereign Hive: Content Vault Importer
 * This tool takes a mass JSON of content generated by The Brain and imports it into the database.
 * Usage: node src/vault_importer.js <content_json_file>
 */

const filePath = process.argv[2];
if (!filePath) {
    console.error('❌ Usage: node src/vault_importer.js <content_json_file>');
    process.exit(1);
}

const client = new Client({
    connectionString: process.env.DATABASE_URL
});

async function importVaultContent() {
    try {
        const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        await client.connect();
        console.log(`📦 Importing ${data.length} content items into the Vault...`);

        for (const item of data) {
            // 1. Find the Account ID
            const accountRes = await client.query('SELECT id FROM accounts WHERE username = $1', [item.username]);
            
            if (accountRes.rows.length === 0) {
                console.warn(`⚠️ Warning: Account [${item.username}] not found. Skipping item.`);
                continue;
            }

            const accountId = accountRes.rows[0].id;

            // 2. Insert into content_vault
            const query = `
                INSERT INTO content_vault (account_id, content, media_urls, framework, topic, status, scheduled_for)
                VALUES ($1, $2, $3, $4, $5, $6, $7)
                RETURNING id;
            `;

            const res = await client.query(query, [
                accountId,
                item.content,
                item.media_urls || [],
                item.framework || 'Standard',
                item.topic || 'General',
                'scheduled', // Default to scheduled
                item.scheduled_for // Expected format: '2026-06-10 09:00:00'
            ]);

            console.log(`✅ [${item.username}] Content vaulted for ${item.scheduled_for} (ID: ${res.rows[0].id})`);
        }

    } catch (err) {
        console.error('❌ Vault Import failed:', err.message);
    } finally {
        await client.end();
    }
}

importVaultContent();
